### ISSUE TITLE
Power Assert no longer shows a helpful output on failures

### ISSUE THREAD

**Issue by ch1c0t** [ch1c0t/hobby-devtools#1]
Doesn't work neither with Minitest
```
     Minitest::Assertion:                  
       load Gem.activate_bin_path('bundler', 'bundle', version)                        
     # /home/ch1c0t/.gem/ruby/2.4.0/gems/minitest-5.10.2/lib/minitest/assertions.rb:139:in `assert'                                                                           
     # /home/ch1c0t/.gem/ruby/2.4.0/gems/minitest-power_assert-0.2.0/lib/minitest/power_assert.rb:12:in `block in assert'                                                     
     # /home/ch1c0t/.gem/ruby/2.4.0/gems/power_assert-1.0.2/lib/power_assert.rb:34:in `start'                                                                                 
     # /home/ch1c0t/.gem/ruby/2.4.0/gems/minitest-power_assert-0.2.0/lib/minitest/power_assert.rb:11:in `assert'                                                              
     # ./spec/main_spec.rb:37:in `block (2 levels) in <top (required)>'                
     # /home/ch1c0t/.gem/ruby/2.4.0/gems/hobby-devtools-0.0.11/lib/hobby/devtools/rspec_helper.rb:14:in `block (2 levels) in <top (required)>'                                
```
nor with RSpec
```
       load Gem.activate_bin_path('bundler', 'bundle', version)                        
     # /home/ch1c0t/.gem/ruby/2.4.0/gems/rspec-power_assert-1.0.0/lib/rspec/power_assert.rb:66:in `handle_result_and_message'                                                 
     # /home/ch1c0t/.gem/ruby/2.4.0/gems/rspec-power_assert-1.0.0/lib/rspec/power_assert.rb:35:in `is_asserted_by'                                                            
     # ./spec/main_spec.rb:37:in `block (2 levels) in <top (required)>'                
     # /home/home/ch1c0t/sources/ruby/hobby-devtools/lib/hobby/devtools/rspec_helper.rb:15:in `block (2 levels) in <top (required)>'                                          
```

**Comment by k-tsj** [comment]
Hi,

I'm a maintainer of power_assert gem.

Could you show me steps to reproduce?
I'll investigate it.

**Comment by ch1c0t** [comment]
Hi, thank you for taking time to do this.

To reproduce, run `bundle exec rspec` in https://github.com/ch1c0t/power_assert_issue_in_hobby-devtools.

The second commit breaks power_assert. So, the issue is likely not in power_assert, but in my code(but I have not understood yet where exactly).

**Comment by ch1c0t** [comment]
The failure message when running `bundle exec rspec` at

[second](https://github.com/ch1c0t/power_assert_issue_in_hobby-devtools/commit/a2c6106ae1338650dd620adb2abcf555f21a5f21) commit:
```
     Failure/Error: assert { one == 0 }
           assert { one == 0 }
```
[first](https://github.com/ch1c0t/power_assert_issue_in_hobby-devtools/commit/2738f1027357398a47d2a8d761bcd491f7ae3f6f) commit:
```
     Failure/Error: assert { one == 0 }                                                                                                 
                                                                                                                                        
           assert { one == 0 }                                                                                                          
                    |   |                                                                                                             
                    |   false
                    1                                                                                                                                   
```

**Comment by k-tsj** [comment]
Thanks, I fixed the issue.

**Comment by ch1c0t** [comment]
Thanks, it works.
